apiVersion: v1
kind: ServiceAccount
metadata:
  # El nombre que usarás para referenciar esta ServiceAccount
  name: cicd-serviceaccount
  # Opcional: El namespace donde se creará. Si se omite, se usará 'default'.
  namespace: adonis-paz-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd
  namespace: adonis-paz-dev
rules:
- apiGroups: ["app"]
  resources: ["deployments"]
  verbs: ["update", "patch", "delete", "create", "get", "list"]